  # We need to test :
# Client access to the repositories (for various targets)
# build-slave configuration
sudo: required

language: bash

env:
  - OSDIR=u1404
  - OSDIR=centos6

services:
  - docker

before_install:
  - git clone --recursive https://github.com/AAROC/DevOps

# Build the container
install:
  - docker build -t ansiblecontainer -f Dockerfile.$OSDIR .

script:
  - docker run -t -P ansiblecontainer ansible-playbook -i /etc/hosts/inventory all -m setup -c local
  - docker run -t -P -v /root/DevOps:/root/DevOps/ -w /root/DevOps/Ansible ansiblecontainer ansible-playbook -c local -i /etc/hosts/inventory ui.yml --skip-tags=slack
# check that ansible is working

after_success:

after_failure:

notifications:
  slack:
    rooms:
      - africa-arabia-roc:qn956vBmV7VIyJ1Xod4Cmnd5#devops
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
