# Docker file for UMD User Interface
#
FROM aaroc/ansiblecontainer:centos6
MAINTAINER Bruce Becker <bbecker@csir.co.za>
WORKDIR /root/
RUN git clone https://github.com/AAROC/DevOps
WORKDIR /root/DevOps/Ansible
CMD echo $'[UIs] \n localhost \n[generic]\nUIs' > inventories/local
RUN ansible-playbook -c local -i inventories/inventory.ui.local ui-container.yml --skip-tags="slack" -e SkipCRLs=true
